### ISSUE TITLE
Meagan's suggested dataset

### ISSUE THREAD

**Issue by meagangardner** [UBC-MDS/dsci_522_group3#1]
Hey Team here's an interesting dataset I found. Predicting student dropout rates based on academic success:
https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success

**Comment by Elshaday-Tamire** [comment]
Hey Team,

Thanks for sharing the Student Dropout and Academic Success dataset! It’s a great idea with real-world impact, especially for improving student outcomes.

I’d like to suggest the Bank Marketing Dataset (https://archive.ics.uci.edu/dataset/222/bank+marketing) instead. It’s also tabular, with a binary classification task (predicting term deposit subscription). Here’s why I think it’s a better fit:

1. Variety of Features
The Bank Marketing Dataset includes a mix of categorical (e.g., job, marital status), numerical (e.g., age, balance), and binary features (e.g., housing loan, personal loan). This diversity allows us to explore a wide range of preprocessing techniques such as one-hot encoding, scaling, and imputation, making it ideal for hands-on learning and experimenting with different machine learning models.

3. Clear Target Variable
 The binary classification task (yes/no) allows us to focus on refining models without the added complexity of multi-class classification, which might be better for a smaller-scale project.

**Comment by Elshaday-Tamire** [comment]
> Hey Team here's an interesting dataset I found. Predicting student dropout rates based on academic success: https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success

Hey Team,

Thanks for sharing the Student Dropout and Academic Success dataset! It’s a great idea with real-world impact, especially for improving student outcomes.

I’d like to suggest the Bank Marketing Dataset (https://archive.ics.uci.edu/dataset/222/bank+marketing) instead. It’s also tabular, with a binary classification task (predicting term deposit subscription). Here’s why I think it’s a better fit:

1. Variety of Features
The Bank Marketing Dataset includes a mix of categorical (e.g., job, marital status), numerical (e.g., age, balance), and binary features (e.g., housing loan, personal loan). This diversity allows us to explore a wide range of preprocessing techniques such as one-hot encoding, scaling, and imputation, making it ideal for hands-on learning and experimenting with different machine learning models.

2. Clear Target Variable
The binary classification task (yes/no) allows us to focus on refining models without the added complexity of multi-class classification, which might be better for a smaller-scale project.

**Comment by meagangardner** [comment]
Hi Elshaday,

Thank you for the feedback! Your reasoning for the Bank Marketing Dataset makes complete sense to me. I agree it looks like there are some interesting features in the dataset that will make creating a prediction model very interesting for this project!
