### ISSUE TITLE
updating conda environment

### ISSUE THREAD

**Issue by meagangardner** [UBC-MDS/dsci_522_group3#16]
Hi team,

Based on tiffany's feedback given on slack, i've gone through and updated the conda environment and lock file to include the version numbers

**Comment by Elshaday-Tamire** [comment]
Cool now I will proceed with the docker environment setup.

**Comment by Elshaday-Tamire** [comment]
I updated the environment file to include the seaborn package, which was installed using pip and was not initially captured by our conda lock file.
