### ISSUE TITLE
Update Environment, Docker Configuration, and Testing Completed – Ready for Review

### ISSUE THREAD

**Issue by Elshaday-Tamire** [UBC-MDS/dsci_522_group3#19]
Hello Team,

I’ve made the following updates to the project:

**1. Environment File:**

* Updated the environment file to include the seaborn package.
* Created the Conda lock file based on the updated environment.
* Note: The Conda lock file didn’t capture seaborn previously as it was installed via pip.

**2. Docker Updates:**

* Edited the Dockerfile to ensure it activates the specific environment we need.
* Added a docker-compose file for better configuration and management.

**3. Testing:**

* Built the Docker image and tested the analysis file.
* Everything is working as expected.

**Next Steps:**
* Please replicate the steps to verify functionality on your end.
* If all works well, kindly accept my pull request.

Thanks! 🚀

**Comment by meagangardner** [comment]
Hi Elshaday, this looks fantastic, thank you for doing that work! I merged the pull request and will check that everything is working as expected from my end as well.

**Comment by meagangardner** [comment]
The environment loaded and I was able to open the dockerfile!
