### ISSUE TITLE
Team Meeting Notes

### ISSUE THREAD

**Issue by meagangardner** [UBC-MDS/dsci_522_group3#25]
Hi Team 
Here are a few quick notes from the meeting today:
- Update dockerfile to have: RUN pip install deepchecks==0.18.1
- Update environment.yml file package versions so there are no conflicts
- Update README file with new Docker loading instructions

**Comment by meagangardner** [comment]
We should also update our docker-compose.yml file with Tiffany's suggestions on slack

**Comment by Elshaday-Tamire** [comment]
done the task "Update dockerfile to have: RUN pip install deepchecks==0.18.1"

**Comment by meagangardner** [comment]
Thank you! I will update the README file

**Comment by meagangardner** [comment]
README file is updated, pulled request sent. I am going to close this issue now - thank you!
