### ISSUE TITLE
script splits 

### ISSUE THREAD

**Issue by henryha2019** [UBC-MDS/dsci_522_group3#37]
- [x] 1. Read and download the data.
    - COMPLETED BY: Meagan
- [x] #42
    - COMPLETED BY: Elshaday
- [x] #44
    - COMPLETED BY: Elshaday
- [x] #45
- [x] #46
Additionally, please create a script and update the corresponding README file to provide clear instructions for others on how to use the script.

**Comment by meagangardner** [comment]
Thank you Henry, I will do the reading in script :)

**Comment by henryha2019** [comment]
I will take on the: Evaluate the model.
I also just realized that items 2 and 3 should be in reverse order my apologies

**Comment by Elshaday-Tamire** [comment]
done with the scripts for cleaning, validating, pre processing splitting and EDA.

**Comment by henryha2019** [comment]
all scripts should be done
