### ISSUE TITLE
Issue Title: Added Test Suite for read_zip Function

### ISSUE THREAD

**Issue by Elshaday-Tamire** [UBC-MDS/dsci_522_group3#69]
Hi team I added a test for read_zip function with the following test cases. 
### Test Cases
1. Local ZIP File Test:
    * Verify extraction of files from a nested ZIP structure.
2. Remote ZIP File Test:
    * Mock HTTP responses to simulate downloading a ZIP file from a URL.
3. Empty ZIP File Test:
    * Confirm appropriate error handling for empty ZIP files.
4. Missing ZIP File Test:
    * Check that a FileNotFoundError is raised for missing outer ZIP files.
5. Invalid ZIP Format Test:
    * Validate that a zipfile.BadZipFile exception is raised for corrupted or non-ZIP files.

**Comment by meagangardner** [comment]
Thank you Elshaday! I have merged your pull request. Great work :)
