### ISSUE TITLE
setting up the data folder

### ISSUE THREAD

**Issue by meagangardner** [UBC-MDS/dsci_522_group3#8]
Hi Everyone
I went into the anaylsis file and set up so split data and scaled data are saved to a preprocessed folder in csv format.
However, we still need to read in the data into a raw file. Is someone able to do this? We should be able to add the package containing the data to our environment file.

**Comment by Elshaday-Tamire** [comment]
> Hi Everyone I went into the anaylsis file and set up so split data and scaled data are saved to a preprocessed folder in csv format. However, we still need to read in the data into a raw file. Is someone able to do this? We should be able to add the package containing the data to our environment file.

Done
